### ISSUE TITLE
Chrome animation overflow bug!

### ISSUE THREAD

**Issue by phlegx** [michalsnik/vue-content-placeholders#11]
Hi

The placeholder animation overflows in the actual Chrome version.

![chrome-bug](https://user-images.githubusercontent.com/111506/61538004-c3b7bd80-aa38-11e9-925b-b26c42f5cfba.png)

**Comment by phlegx** [comment]
Can be solved with:

```scss
@mixin vue-content-placeholders {
  position: relative;
  overflow: hidden; /* Other browser*/
  overflow: overlay; /* Chrome */
  z-index: 1;
  ...
}
```

**Comment by phlegx** [comment]
Solved with:

```scss
@mixin vue-content-placeholders {
  position: relative;
  overflow: hidden;  /* Other browsers */
  overflow: overlay; /* Chrome */
  &::-webkit-scrollbar {
      width: 0;
      height: 0;
  }
  ...
}
```

PR: michalsnik/vue-content-placeholders/pull/12
