### ISSUE TITLE
Change the color of the placeholder?

### ISSUE THREAD

**Issue by mhetreramesh** [michalsnik/vue-content-placeholders#16]
Is this possible to change the color of the placeholder? I would like to use it in the dark more with more dark color?

**Comment by LeCoupa** [comment]
You can update the color like this:

```css
.vue-content-placeholders-img,
.vue-content-placeholders-text__line {
    background: red !important;
}
```
